# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow:
    has_velocity_limits: true
    max_velocity: 4.5378560552
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder:
    has_velocity_limits: true
    max_velocity: 6.4577182324
    has_acceleration_limits: false
    max_acceleration: 0
  wrist1:
    has_velocity_limits: true
    max_velocity: 7.1558499332
    has_acceleration_limits: false
    max_acceleration: 0
  wrist2:
    has_velocity_limits: true
    max_velocity: 9.599310886
    has_acceleration_limits: false
    max_acceleration: 0
  wrist3:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  wrist4:
    has_velocity_limits: true
    max_velocity: 17.45329252
    has_acceleration_limits: false
    max_acceleration: 0